# Generated by Django 4.2.6 on 2023-10-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0005_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
    ]
